# Generated by Django 5.2.3 on 2025-06-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0003_match_matchplayer_match_players"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="matchplayer",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="matchplayer",
            constraint=models.UniqueConstraint(
                fields=("match", "player"), name="unique_player_per_match"
            ),
        ),
    ]
